set(PRODDL_BUILD_TOP C:/proddl CACHE INTERNAL "")
set(CMAKE_CXX_FLAGS "/DBOOST_ALL_DYN_LINK /D_SCL_SECURE_NO_WARNINGS /bigobj /EHsc /D_HDF5USEDLL_ /DWIN32 /DGSL_DLL" CACHE INTERNAL "")
set(PRODDL_DEPS_BUILD_HOME ${PRODDL_BUILD_TOP}/deps_build CACHE INTERNAL "")
set(PRODDL_DEPS_HOME ${PRODDL_BUILD_TOP}/deps CACHE INTERNAL "")
set(CGAL_DIR ${PRODDL_DEPS_HOME}/CGAL-4.1 CACHE INTERNAL "")
set(FFTW3_DIR ${PRODDL_DEPS_HOME}/fftw3_32 CACHE INTERNAL "")
set(FFTW_ROOT ${PRODDL_DEPS_HOME} CACHE INTERNAL "Helps FindFFTW")
set(fftw3_LIBRARY ${FFTW3_DIR}/libfftw3-3.lib CACHE INTERNAL "")
set(fftw3f_LIBRARY ${FFTW3_DIR}/libfftw3f-3.lib CACHE INTERNAL "")
set(FFTW_LIBRARIES ${fftw3_LIBRARY} ${fftw3f_LIBRARY} CACHE INTERNAL "")
set(HDF5_DIR ${PRODDL_DEPS_HOME}/HDF5_1.8.10 CACHE INTERNAL "")
set(OpenCV_DIR ${PRODDL_DEPS_HOME}/OpenCV2.2 CACHE INTERNAL "")
set(SWIG_DIR ${PRODDL_DEPS_BUILD_HOME}/swigwin-2.0.9 CACHE INTERNAL "")
set(HDF5_ROOT ${HDF5_DIR} CACHE INTERNAL "")
#set(HDF5_LIBRARIES ${PRODDL_DEPS_HOME}/bin/hdf5dll.lib CACHE INTERNAL "")
#IMP uses this
set(HDF5_C_LIBRARY ${PRODDL_DEPS_HOME}/bin/hdf5dll.lib CACHE INTERNAL "")
#current built in FindHDF5 module would define this
set(HDF5_C_LIBRARIES ${PRODDL_DEPS_HOME}/bin/hdf5dll.lib CACHE INTERNAL "")
#set(HDF5_INCLUDE_DIRS ${HDF5_DIR}/include CACHE INTERNAL "")
#set(gsl_LIBRARY ${PRODDL_DEPS_HOME}/bin/libgsl.lib CACHE FILEPATH "")
#set(gslcblas_LIBRARY ${PRODDL_DEPS_HOME}/bin/libgslcblas.lib CACHE FILEPATH "")

set(CMAKE_PREFIX_PATH
	${PRODDL_DEPS_HOME}
	${HDF5_DIR} 
	${HDF5_DIR}/cmake/hdf5 
	${OpenCV_DIR}
#	${OPENCV_DIR}/build
#	${OPENCV_DIR}/build/x86/vc10
	${PRODDL_DEPS_HOME}/GnuWin32
	${FFTW3_DIR} CACHE INTERNAL "")
#set(CGAL_DONT_OVERRIDE_CMAKE_FLAGS FALSE CACHE INTERNAL "")
#HDF5/bin dir should be in the PATH to avoid "Fatal error, corrupt file when linking hdf5.dll
#set(ENV{PATH} "$ENV{PATH};${PRODDL_DEPS_HOME}/bin;${SWIG_DIR};${HDF5_DIR}/bin" CACHE INTERNAL "")
#set(ENV{PATH} "$ENV{PATH};${PRODDL_DEPS_HOME}/bin;${SWIG_DIR}" CACHE INTERNAL "")
#set(CMAKE_BUILD_TYPE Release CACHE INTERNAL "Build Type")
#MESSAGE("PATH=$ENV{PATH}")
#MESSAGE("CMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}")
include_directories(${PRODDL_DEPS_HOME}/include ${PRODDL_DEPS_HOME}/include/opencv ${PRODDL_DEPS_HOME}/include/opencv2)
link_directories(${PRODDL_DEPS_HOME}/bin)
#include(${OpenCV_DIR}/OpenCVConfig.cmake)

set(CMAKE_INSTALL_PREFIX ${PRODDL_BUILD_TOP}/proddl2_inst CACHE INTERNAL "")
set(CMAKE_VERBOSE_MAKEFILE ON CACHE INTERNAL "")
MESSAGE("Toolchain file loaded")
