set PRODDL_BUILD_TOP=C:\proddl
set PRODDL_DEPS=%PRODDL_BUILD_TOP%\deps
set PRODDL_DEPS_BUILD=%PRODDL_BUILD_TOP%\deps_build
set PDODDL_SWIG_ROOT=%PRODDL_DEPS_BUILD%\swigwin-2.0.9
set PDODDL_DOXYGEN_ROOT=%PRODDL_DEPS_BUILD%\doxygen

set BOOST_ROOT=%PRODDL_DEPS%\boost_1_44

set IMP_HOME=%PRODDL_DEPS%\IMP

PATH=%PATH%;%IMP_HOME%\bin;%PDODDL_SWIG_ROOT%;%PRODDL_DOXYGEN_ROOT%\bin;%PRODDL_DEPS%\bin;%PRODDL_DEPS\HDF5_1.8.10\bin

set PYTHONPATH=%PYTHONPATH%;%IMP_HOME%\python;%IMP_HOME%\bin
